In [1]:
import numpy as np

# Step 1: Define X and y
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

y = np.array([1, 2, 3])  # Shape (3,)

# Step 2: Set regularization parameter
lambda_ = 1.0

# Step 3: Compute ridge regression closed-form solution
n_features = X.shape[1]
identity = np.eye(n_features)

# Ridge regression formula: beta = (X^T X + λI)^(-1) X^T y
XTX = X.T @ X
XTy = X.T @ y
ridge_matrix = XTX + lambda_ * identity
beta = np.linalg.inv(ridge_matrix) @ XTy

# Print results
print("X^T X + λI:\n", ridge_matrix)
print("\nX^T y:\n", XTy)
print("\nRidge Regression Coefficients (β):\n", beta)


X^T X + λI:
 [[ 67.  78.  90.]
 [ 78.  94. 108.]
 [ 90. 108. 127.]]

X^T y:
 [30 36 42]

Ridge Regression Coefficients (β):
 [0.01967213 0.11803279 0.21639344]
